B_Simeon_Chakarov_24-2/config/routes.rb
Rails.application.routes.draw do
  resources :table_bottles
  resources :tables
  resources :bottles
  get "/B_24_Simeon_Chakarov_table_bottles", to: "table_bottles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B_Simeon_Chakarov_24-2/app/models/bottle.rb
class Bottle < ApplicationRecord
	has_many :table_bottles
	has_many :tables, through: :table_bottles
	validates :brand , uniqueness: true
	validates_presence_of :table_id
end

B_Simeon_Chakarov_24-2/app/models/table.rb
class Table < ApplicationRecord
	has_many :table_bottles
	has_many :bottles, through: :table_bottles
end

B_Simeon_Chakarov_24-2/app/models/table_bottle.rb
class TableBottle < ApplicationRecord
	belongs_to :bottle
	belongs_to :table
end

B_Simeon_Chakarov_24-2/app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :set_bottle, only: [:show, :edit, :update, :destroy]

  # GET /bottles
  # GET /bottles.json
  def index
    @bottles = Bottle.all
  end

  # GET /bottles/1
  # GET /bottles/1.json
  def show
  end

  # GET /bottles/new
  def new
    @bottle = Bottle.new
  end

  # GET /bottles/1/edit
  def edit
  end

  # POST /bottles
  # POST /bottles.json
  def create
    @bottle = Bottle.new(bottle_params)

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to @bottle, notice: 'Bottle was successfully created.' }
        format.json { render :show, status: :created, location: @bottle }
      else
        format.html { render :new }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottles/1
  # PATCH/PUT /bottles/1.json
  def update
    respond_to do |format|
      if @bottle.update(bottle_params)
        format.html { redirect_to @bottle, notice: 'Bottle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bottle }
      else
        format.html { render :edit }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.json
  def destroy
    @bottle.destroy
    respond_to do |format|
      format.html { redirect_to bottles_url, notice: 'Bottle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle
      @bottle = Bottle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bottle_params
      params.require(:bottle).permit(:color, :brand, :table_id)
    end
end

B_Simeon_Chakarov_24-2/app/controllers/table_bottles_controller.rb
class TableBottlesController < ApplicationController
  before_action :set_table_bottle, only: [:show, :edit, :update, :destroy]

  # GET /table_bottles
  # GET /table_bottles.json
  def index
    @table_bottles = TableBottle.all
    @tabels = Table.all
    @bottles = Bottle.all
  end

  # GET /table_bottles/1
  # GET /table_bottles/1.json
  def show
  end

  # GET /table_bottles/new
  def new
    @table_bottle = TableBottle.new
  end

  # GET /table_bottles/1/edit
  def edit
  end

  # POST /table_bottles
  # POST /table_bottles.json
  def create
    @table_bottle = TableBottle.new(table_bottle_params)

    respond_to do |format|
      if @table_bottle.save
        format.html { redirect_to @table_bottle, notice: 'Table bottle was successfully created.' }
        format.json { render :show, status: :created, location: @table_bottle }
      else
        format.html { render :new }
        format.json { render json: @table_bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_bottles/1
  # PATCH/PUT /table_bottles/1.json
  def update
    respond_to do |format|
      if @table_bottle.update(table_bottle_params)
        format.html { redirect_to @table_bottle, notice: 'Table bottle was successfully updated.' }
        format.json { render :show, status: :ok, location: @table_bottle }
      else
        format.html { render :edit }
        format.json { render json: @table_bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_bottles/1
  # DELETE /table_bottles/1.json
  def destroy
    @table_bottle.destroy
    respond_to do |format|
      format.html { redirect_to table_bottles_url, notice: 'Table bottle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_bottle
      @table_bottle = TableBottle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_bottle_params
      params.require(:table_bottle).permit(:table_id, :bottle_id)
    end
end

B_Simeon_Chakarov_24-2/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:width, :height)
    end
end

B_Simeon_Chakarov_24-2/app/helpers/bottles_helper.rb
module BottlesHelper
end

B_Simeon_Chakarov_24-2/app/helpers/table_bottles_helper.rb
module TableBottlesHelper
end

B_Simeon_Chakarov_24-2/app/helpers/tables_helper.rb
module TablesHelper
end

B_Simeon_Chakarov_24-2/app/views/bottles/_form.html.erb
<%= form_with(model: bottle, local: true) do |form| %>
  <% if bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
      <% bottle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :bottle_color %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :bottle_brand %>
  </div>

  <div class="field">
    <%= form.label :table_id %>
    <%= form.number_field :table_id, id: :bottle_table_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_Simeon_Chakarov_24-2/app/views/bottles/edit.html.erb
<h1>Editing Bottle</h1>

<%= render 'form', bottle: @bottle %>

<%= link_to 'Show', @bottle %> |
<%= link_to 'Back', bottles_path %>

B_Simeon_Chakarov_24-2/app/views/bottles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bottles</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Brand</th>
      <th>Table</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bottles.each do |bottle| %>
      <tr>
        <td><%= bottle.color %></td>
        <td><%= bottle.brand %></td>
        <td><%= bottle.table_id %></td>
        <td><%= link_to 'Show', bottle %></td>
        <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
        <td><%= link_to 'Destroy', bottle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bottle', new_bottle_path %>

B_Simeon_Chakarov_24-2/app/views/bottles/new.html.erb
<h1>New Bottle</h1>

<%= render 'form', bottle: @bottle %>

<%= link_to 'Back', bottles_path %>

B_Simeon_Chakarov_24-2/app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @bottle.color %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @bottle.brand %>
</p>

<p>
  <strong>Table:</strong>
  <%= @bottle.table_id %>
</p>

<%= link_to 'Edit', edit_bottle_path(@bottle) %> |
<%= link_to 'Back', bottles_path %>

B_Simeon_Chakarov_24-2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BSimeonChakarov242</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

B_Simeon_Chakarov_24-2/app/views/table_bottles/_form.html.erb
<%= form_with(model: table_bottle, local: true) do |form| %>
  <% if table_bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table_bottle.errors.count, "error") %> prohibited this table_bottle from being saved:</h2>

      <ul>
      <% table_bottle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :table_id %>
    <%= form.number_field :table_id, id: :table_bottle_table_id %>
  </div>

  <div class="field">
    <%= form.label :bottle_id %>
    <%= form.number_field :bottle_id, id: :table_bottle_bottle_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_Simeon_Chakarov_24-2/app/views/table_bottles/edit.html.erb
<h1>Editing Table Bottle</h1>

<%= render 'form', table_bottle: @table_bottle %>

<%= link_to 'Show', @table_bottle %> |
<%= link_to 'Back', table_bottles_path %>

B_Simeon_Chakarov_24-2/app/views/table_bottles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Table Bottles</h1>

<table>
  <thead>
    <tr>
      <th>Table</th>
      <th>Bottle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @table_bottles.each do |table_bottle| %>
      <tr>
       	<td><%= table_bottle.bottle.color %></td>
        <td><%= table_bottle.bottle.brand %></td>
        <td><%= table_bottle.table.height %></td>
        <td><%= table_bottle.table.width %></td>
        <td><%= table_bottle.table_id %></td>
        
        <td><%= link_to 'Show', table_bottle %></td>
        <td><%= link_to 'Edit', edit_table_bottle_path(table_bottle) %></td>
        <td><%= link_to 'Destroy', table_bottle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table Bottle', new_table_bottle_path %>

B_Simeon_Chakarov_24-2/app/views/table_bottles/new.html.erb
<h1>New Table Bottle</h1>

<%= render 'form', table_bottle: @table_bottle %>

<%= link_to 'Back', table_bottles_path %>

B_Simeon_Chakarov_24-2/app/views/table_bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table:</strong>
  <%= @table_bottle.table_id %>
</p>

<p>
  <strong>Bottle:</strong>
  <%= @table_bottle.bottle_id %>
</p>

<%= link_to 'Edit', edit_table_bottle_path(@table_bottle) %> |
<%= link_to 'Back', table_bottles_path %>

B_Simeon_Chakarov_24-2/app/views/tables/_form.html.erb
<%= form_with(model: table, local: true) do |form| %>
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width, id: :table_width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height, id: :table_height %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_Simeon_Chakarov_24-2/app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

B_Simeon_Chakarov_24-2/app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tables</h1>

<table>
  <thead>
    <tr>
      <th>Width</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.width %></td>
        <td><%= table.height %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

B_Simeon_Chakarov_24-2/app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Back', tables_path %>

B_Simeon_Chakarov_24-2/app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Width:</strong>
  <%= @table.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @table.height %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>