B_24_Simeon_Chakarov/config/routes.rb
Rails.application.routes.draw do
  resources :teacher_schoolclasses
  resources :schoolclasses
  resources :teachers
  get "/B_24_Simeon_Chakarov_teacher_schoolclasses", to: "teacher_schoolclasses#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B_24_Simeon_Chakarov/app/models/schoolclass.rb
class Schoolclass < ApplicationRecord
	has_many :teacher_schoolclasses
	has_many :teachers, through: :teacher_schoolclasses
	validates_presence_of :teacher_id
end

B_24_Simeon_Chakarov/app/models/teacher.rb
class Teacher < ApplicationRecord
	has_many :teacher_schoolclasses
	has_many :schoolclasses, through: :teacher_schoolclasses
	validates :firstname , uniqueness: true
	validates :middlename, uniqueness: true
end

B_24_Simeon_Chakarov/app/models/teacher_schoolclass.rb
class TeacherSchoolclass < ApplicationRecord
	belongs_to :schoolclass
	belongs_to :teacher
end

B_24_Simeon_Chakarov/app/controllers/schoolclasses_controller.rb
class SchoolclassesController < ApplicationController
  before_action :set_schoolclass, only: [:show, :edit, :update, :destroy]

  # GET /schoolclasses
  # GET /schoolclasses.json
  def index
    @schoolclasses = Schoolclass.all
  end

  # GET /schoolclasses/1
  # GET /schoolclasses/1.json
  def show
  end

  # GET /schoolclasses/new
  def new
    @schoolclass = Schoolclass.new
  end

  # GET /schoolclasses/1/edit
  def edit
  end

  # POST /schoolclasses
  # POST /schoolclasses.json
  def create
    @schoolclass = Schoolclass.new(schoolclass_params)

    respond_to do |format|
      if @schoolclass.save
        format.html { redirect_to @schoolclass, notice: 'Schoolclass was successfully created.' }
        format.json { render :show, status: :created, location: @schoolclass }
      else
        format.html { render :new }
        format.json { render json: @schoolclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schoolclasses/1
  # PATCH/PUT /schoolclasses/1.json
  def update
    respond_to do |format|
      if @schoolclass.update(schoolclass_params)
        format.html { redirect_to @schoolclass, notice: 'Schoolclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @schoolclass }
      else
        format.html { render :edit }
        format.json { render json: @schoolclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schoolclasses/1
  # DELETE /schoolclasses/1.json
  def destroy
    @schoolclass.destroy
    respond_to do |format|
      format.html { redirect_to schoolclasses_url, notice: 'Schoolclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schoolclass
      @schoolclass = Schoolclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schoolclass_params
      params.require(:schoolclass).permit(:day, :teacher_id)
    end
end

B_24_Simeon_Chakarov/app/controllers/teacher_schoolclasses_controller.rb
class TeacherSchoolclassesController < ApplicationController
  before_action :set_teacher_schoolclass, only: [:show, :edit, :update, :destroy]

  # GET /teacher_schoolclasses
  # GET /teacher_schoolclasses.json
  def index
    @teacher_schoolclasses = TeacherSchoolclass.all
    @teachers = Teacher.all
		@schoolclasses = Schoolclass.all
  end

  # GET /teacher_schoolclasses/1
  # GET /teacher_schoolclasses/1.json
  def show
  end

  # GET /teacher_schoolclasses/new
  def new
    @teacher_schoolclass = TeacherSchoolclass.new
  end

  # GET /teacher_schoolclasses/1/edit
  def edit
  end

  # POST /teacher_schoolclasses
  # POST /teacher_schoolclasses.json
  def create
    @teacher_schoolclass = TeacherSchoolclass.new(teacher_schoolclass_params)

    respond_to do |format|
      if @teacher_schoolclass.save
        format.html { redirect_to @teacher_schoolclass, notice: 'Teacher schoolclass was successfully created.' }
        format.json { render :show, status: :created, location: @teacher_schoolclass }
      else
        format.html { render :new }
        format.json { render json: @teacher_schoolclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teacher_schoolclasses/1
  # PATCH/PUT /teacher_schoolclasses/1.json
  def update
    respond_to do |format|
      if @teacher_schoolclass.update(teacher_schoolclass_params)
        format.html { redirect_to @teacher_schoolclass, notice: 'Teacher schoolclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher_schoolclass }
      else
        format.html { render :edit }
        format.json { render json: @teacher_schoolclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teacher_schoolclasses/1
  # DELETE /teacher_schoolclasses/1.json
  def destroy
    @teacher_schoolclass.destroy
    respond_to do |format|
      format.html { redirect_to teacher_schoolclasses_url, notice: 'Teacher schoolclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher_schoolclass
      @teacher_schoolclass = TeacherSchoolclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_schoolclass_params
      params.require(:teacher_schoolclass).permit(:teacher_id, :schoolclass_id)
    end
end

B_24_Simeon_Chakarov/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:firstname, :middlename, :title, :subject)
    end
end

B_24_Simeon_Chakarov/app/helpers/schoolclasses_helper.rb
module SchoolclassesHelper
end

B_24_Simeon_Chakarov/app/helpers/teacher_schoolclasses_helper.rb
module TeacherSchoolclassesHelper
end

B_24_Simeon_Chakarov/app/helpers/teachers_helper.rb
module TeachersHelper
end

B_24_Simeon_Chakarov/app/views/schoolclasses/_form.html.erb
<%= form_with(model: schoolclass, local: true) do |form| %>
  <% if schoolclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schoolclass.errors.count, "error") %> prohibited this schoolclass from being saved:</h2>

      <ul>
      <% schoolclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day %>
    <%= form.text_field :day, id: :schoolclass_day %>
  </div>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.number_field :teacher_id, id: :schoolclass_teacher_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_24_Simeon_Chakarov/app/views/schoolclasses/edit.html.erb
<h1>Editing Schoolclass</h1>

<%= render 'form', schoolclass: @schoolclass %>

<%= link_to 'Show', @schoolclass %> |
<%= link_to 'Back', schoolclasses_path %>

B_24_Simeon_Chakarov/app/views/schoolclasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schoolclasses</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schoolclasses.each do |schoolclass| %>
      <tr>
        <td><%= schoolclass.day %></td>
        <td><%= schoolclass.teacher_id %></td>
        <td><%= link_to 'Show', schoolclass %></td>
        <td><%= link_to 'Edit', edit_schoolclass_path(schoolclass) %></td>
        <td><%= link_to 'Destroy', schoolclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schoolclass', new_schoolclass_path %>

B_24_Simeon_Chakarov/app/views/schoolclasses/new.html.erb
<h1>New Schoolclass</h1>

<%= render 'form', schoolclass: @schoolclass %>

<%= link_to 'Back', schoolclasses_path %>

B_24_Simeon_Chakarov/app/views/schoolclasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @schoolclass.day %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @schoolclass.teacher_id %>
</p>

<%= link_to 'Edit', edit_schoolclass_path(@schoolclass) %> |
<%= link_to 'Back', schoolclasses_path %>

B_24_Simeon_Chakarov/app/views/teacher_schoolclasses/_form.html.erb
<%= form_with(model: teacher_schoolclass, local: true) do |form| %>
  <% if teacher_schoolclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher_schoolclass.errors.count, "error") %> prohibited this teacher_schoolclass from being saved:</h2>

      <ul>
      <% teacher_schoolclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.number_field :teacher_id, id: :teacher_schoolclass_teacher_id %>
  </div>

  <div class="field">
    <%= form.label :schoolclass_id %>
    <%= form.number_field :schoolclass_id, id: :teacher_schoolclass_schoolclass_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_24_Simeon_Chakarov/app/views/teacher_schoolclasses/edit.html.erb
<h1>Editing Teacher Schoolclass</h1>

<%= render 'form', teacher_schoolclass: @teacher_schoolclass %>

<%= link_to 'Show', @teacher_schoolclass %> |
<%= link_to 'Back', teacher_schoolclasses_path %>

B_24_Simeon_Chakarov/app/views/teacher_schoolclasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teacher Schoolclasses</h1>

<table>
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Schoolclass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teacher_schoolclasses.each do |teacher_schoolclass| %>
      <tr>
        <td><%= teacher_schoolclass.teacher.firstname %></td>
         <td><%= teacher_schoolclass.teacher.title %></td>
        <td><%= teacher_schoolclass.schoolclass.day%></td>
      </tr>
<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher Schoolclass', new_teacher_schoolclass_path %>

B_24_Simeon_Chakarov/app/views/teacher_schoolclasses/new.html.erb
<h1>New Teacher Schoolclass</h1>

<%= render 'form', teacher_schoolclass: @teacher_schoolclass %>

<%= link_to 'Back', teacher_schoolclasses_path %>

B_24_Simeon_Chakarov/app/views/teacher_schoolclasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @teacher_schoolclass.teacher_id %>
</p>

<p>
  <strong>Schoolclass:</strong>
  <%= @teacher_schoolclass.schoolclass_id %>
</p>

<%= link_to 'Edit', edit_teacher_schoolclass_path(@teacher_schoolclass) %> |
<%= link_to 'Back', teacher_schoolclasses_path %>

B_24_Simeon_Chakarov/app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :teacher_firstname %>
  </div>

  <div class="field">
    <%= form.label :middlename %>
    <%= form.text_field :middlename, id: :teacher_middlename %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :teacher_title %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :teacher_subject %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_24_Simeon_Chakarov/app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

B_24_Simeon_Chakarov/app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Middlename</th>
      <th>Title</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.firstname %></td>
        <td><%= teacher.middlename %></td>
        <td><%= teacher.title %></td>
        <td><%= teacher.subject %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

B_24_Simeon_Chakarov/app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

B_24_Simeon_Chakarov/app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @teacher.firstname %>
</p>

<p>
  <strong>Middlename:</strong>
  <%= @teacher.middlename %>
</p>

<p>
  <strong>Title:</strong>
  <%= @teacher.title %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @teacher.subject %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>