B_24_Simeon_Chakarov-3/config/routes.rb
Rails.application.routes.draw do
  resources :member_teams
  resources :members
  resources :teams
  get "/B_24_Simeon_Chakarov_member_teams", to: "member_teams#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B_24_Simeon_Chakarov-3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

B_24_Simeon_Chakarov-3/app/models/member.rb
class Member < ApplicationRecord
	has_many :member_teams
	has_many :teams, through: :member_teams
	validates :email , uniqueness: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

B_24_Simeon_Chakarov-3/app/models/member_team.rb
class MemberTeam < ApplicationRecord
	belongs_to :team
	belongs_to :member
	
	validate do 
		if has_team_with_color? Team.find(self.team_id).color
				errors.add(:team, "There is already team with this color")
		end
	end
	
	private
	def has_team_with_color? color
	MemberTeam.where(member_id: self.member_id).each do |mt|
		if color==Team.find(mt.team_id).color
			return true
		end
	end
	false
	end
end

B_24_Simeon_Chakarov-3/app/models/team.rb
class Team < ApplicationRecord
	has_many :member_teams
	has_many :members, through: :member_teams
end

B_24_Simeon_Chakarov-3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

B_24_Simeon_Chakarov-3/app/controllers/member_teams_controller.rb
class MemberTeamsController < ApplicationController
  before_action :set_member_team, only: [:show, :edit, :update, :destroy]

  # GET /member_teams
  # GET /member_teams.json
  def index
    @member_teams = MemberTeam.all
	@members = Member.all
	@members = Team.all
  end

  # GET /member_teams/1
  # GET /member_teams/1.json
  def show
  end

  # GET /member_teams/new
  def new
    @member_team = MemberTeam.new
  end

  # GET /member_teams/1/edit
  def edit
  end

  # POST /member_teams
  # POST /member_teams.json
  def create
    @member_team = MemberTeam.new(member_team_params)

    respond_to do |format|
      if @member_team.save
        format.html { redirect_to @member_team, notice: 'Member team was successfully created.' }
        format.json { render :show, status: :created, location: @member_team }
      else
        format.html { render :new }
        format.json { render json: @member_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_teams/1
  # PATCH/PUT /member_teams/1.json
  def update
    respond_to do |format|
      if @member_team.update(member_team_params)
        format.html { redirect_to @member_team, notice: 'Member team was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_team }
      else
        format.html { render :edit }
        format.json { render json: @member_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_teams/1
  # DELETE /member_teams/1.json
  def destroy
    @member_team.destroy
    respond_to do |format|
      format.html { redirect_to member_teams_url, notice: 'Member team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_team
      @member_team = MemberTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_team_params
      params.require(:member_team).permit(:team_id, :member_id)
    end
end

B_24_Simeon_Chakarov-3/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email)
    end
end

B_24_Simeon_Chakarov-3/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:color, :name, :number)
    end
end

B_24_Simeon_Chakarov-3/app/helpers/application_helper.rb
module ApplicationHelper
end

B_24_Simeon_Chakarov-3/app/helpers/member_teams_helper.rb
module MemberTeamsHelper
end

B_24_Simeon_Chakarov-3/app/helpers/members_helper.rb
module MembersHelper
end

B_24_Simeon_Chakarov-3/app/helpers/teams_helper.rb
module TeamsHelper
end

B_24_Simeon_Chakarov-3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B24SimeonChakarov</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

B_24_Simeon_Chakarov-3/app/views/member_teams/_form.html.erb
<%= form_with(model: member_team, local: true) do |form| %>
  <% if member_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member_team.errors.count, "error") %> prohibited this member_team from being saved:</h2>

      <ul>
      <% member_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id, id: :member_team_team_id %>
  </div>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.number_field :member_id, id: :member_team_member_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_24_Simeon_Chakarov-3/app/views/member_teams/edit.html.erb
<h1>Editing Member Team</h1>

<%= render 'form', member_team: @member_team %>

<%= link_to 'Show', @member_team %> |
<%= link_to 'Back', member_teams_path %>

B_24_Simeon_Chakarov-3/app/views/member_teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Member Teams</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @member_teams.each do |member_team| %>
      <tr>
        <td><%= member_team.team.name %></td>
        <td><%= member_team.member.name %></td>
        <td><%= link_to 'Show', member_team %></td>
        <td><%= link_to 'Edit', edit_member_team_path(member_team) %></td>
        <td><%= link_to 'Destroy', member_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member Team', new_member_team_path %>

B_24_Simeon_Chakarov-3/app/views/member_teams/new.html.erb
<h1>New Member Team</h1>

<%= render 'form', member_team: @member_team %>

<%= link_to 'Back', member_teams_path %>

B_24_Simeon_Chakarov-3/app/views/member_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @member_team.team_id %>
</p>

<p>
  <strong>Member:</strong>
  <%= @member_team.member_id %>
</p>

<%= link_to 'Edit', edit_member_team_path(@member_team) %> |
<%= link_to 'Back', member_teams_path %>

B_24_Simeon_Chakarov-3/app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :member_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B_24_Simeon_Chakarov-3/app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

B_24_Simeon_Chakarov-3/app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

B_24_Simeon_Chakarov-3/app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

B_24_Simeon_Chakarov-3/app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>